package com.example.authservice.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.Collections;

/**
 * A registered account, and the principal Spring Security authenticates against.
 *
 * <p>Getters and setters are generated by Lombok, so they are callable but do not appear in this
 * source file.
 *
 * <p>Both {@code email} and {@code phoneNumber} are unique and nullable. Unique because each is a
 * destination for a 2FA code: two accounts sharing a number would mean one person's phone can
 * complete the other person's login. Nullable because accounts registered before those fields
 * existed have neither, and Postgres permits any number of nulls under a unique constraint, so
 * those rows are unaffected — notification listeners skip a user with no address rather than
 * inventing one. Phone numbers must be stored already normalized to E.164, or the uniqueness
 * constraint compares two spellings of the same number as different values.
 *
 * <p>The {@code UserDetails} account-status flags below are all hardcoded to permit login: this
 * service implements neither account lockout nor role-based authorities, so no caller should read a
 * granted authority or an unlocked flag as evidence that either mechanism ran.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
public class User implements UserDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String username;

    @Column(nullable = false)
    private String password;

    @Column(unique = true)
    private String phoneNumber;

    @Column(unique = true)
    private String email;

    private Boolean totpEnabled = false;
    private String totpSecret;

    /**
     * Returns no authorities, because this service does not model roles.
     *
     * <p>Always empty, never {@code null}. Any authorization rule written against a role or scope
     * will therefore always deny; access control here is by endpoint, not by authority.
     *
     * @return an immutable empty collection
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return Collections.emptyList();
    }

    @Override
    public boolean isAccountNonExpired() { return true; }

    @Override
    public boolean isAccountNonLocked() { return true; }

    @Override
    public boolean isCredentialsNonExpired() { return true; }

    @Override
    public boolean isEnabled() { return true; }
}